### ISSUE TITLE
Discord Appeal

### ISSUE THREAD

**Issue by Nopock** [Florial-Development/FlorialS6#1]
Hello I am false ban from discord

**Comment by SelSung** [comment]
Hello! This is Sel, What were you banned for? And why do you think its false?

**Comment by Nopock** [comment]
I was banned for unknown and I used to be developer here and I resigned

**Comment by SelSung** [comment]
What is your Discord user and tag?

**Comment by gtalovebitches** [comment]
> I was banned for unknown and I used to be developer here and I resigned

Staff manager here, why were you banned and what's your discord tag?

**Comment by Nopock** [comment]
> > I was banned for unknown and I used to be developer here and I resigned
> 
> Staff manager here, why were you banned and what's your discord tag?

Nopox#5829 and I am still unaware of the reason

**Comment by gtalovebitches** [comment]
> > > I was banned for unknown and I used to be developer here and I resigned
> > 
> > 
> > Staff manager here, why were you banned and what's your discord tag?
> 
> Nopox#5829 and I am still unaware of the reason

I'll check for you.
